spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fileprocessor
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  email:
    queue: javauploadfile
  exchange:
    name: javauploadfile_exchange
  routingkey:
    name: javauploadfile_routingkey

server:
  port: 8080
